const { expect } = require("chai");
const { ethers } = require("hardhat");

describe("CropTracker (IP-fragmentation style tracking)", function () {
  let tracker, owner, registrar, farmer, distributor, retailer1, retailer2, outsider;
  // identification is generated by the contract, first batch always gets 1
  const BATCH = 1;

  beforeEach(async function () {
    [owner, registrar, farmer, distributor, retailer1, retailer2, outsider] =
      await ethers.getSigners();
    const Tracker = await ethers.getContractFactory("CropTracker");
    tracker = await Tracker.deploy();
    await tracker.waitForDeployment();
    // in production the registrar is the Farmer contract
    await tracker.connect(owner).setRegistrar(registrar.address, true);
  });

  // helper: registrar registers 100kg for the farmer (root = fragment 1),
  // farmer hands the whole lot to the distributor (fragment 2)
  async function registerAndHandOver() {
    await tracker.connect(registrar).registerBatch(farmer.address, 100); // fragment 1 (root)
    await tracker
      .connect(farmer)
      .fragment(1, [100], [distributor.address], [false]); // fragment 2
  }

  describe("registrar / registerBatch", function () {
    it("only the owner sets registrars", async function () {
      await expect(
        tracker.connect(outsider).setRegistrar(outsider.address, true)
      ).to.be.revertedWith("Not owner");
      await expect(
        tracker.connect(owner).setRegistrar(ethers.ZeroAddress, true)
      ).to.be.revertedWith("Zero registrar");
      await expect(tracker.connect(owner).setRegistrar(outsider.address, true))
        .to.emit(tracker, "RegistrarSet")
        .withArgs(outsider.address, true);
      expect(await tracker.isRegistrar(outsider.address)).to.equal(true);
    });

    it("creates a root with offset 0, full size, MF=false, DF=false, owned by the farmer", async function () {
      await expect(tracker.connect(registrar).registerBatch(farmer.address, 100))
        .to.emit(tracker, "BatchRegistered")
        .withArgs(1, farmer.address, BATCH, 100);
      const root = await tracker.getFragment(1);
      expect(root.identification).to.equal(BATCH);
      expect(root.farmer).to.equal(farmer.address);
      expect(root.parentId).to.equal(0);
      expect(root.offset).to.equal(0);
      expect(root.size).to.equal(100);
      expect(root.mf).to.equal(false);
      expect(root.df).to.equal(false);
      expect(root.owner).to.equal(farmer.address);
    });

    it("generates identification itself: 1, 2, 3... for any farmer", async function () {
      await tracker.connect(registrar).registerBatch(farmer.address, 100);
      await tracker.connect(registrar).registerBatch(outsider.address, 40);
      await tracker.connect(registrar).registerBatch(farmer.address, 10);
      expect(await tracker.batchCount()).to.equal(3);
      expect((await tracker.getFragment(1)).parentId).to.equal(0); // each is a root
      expect((await tracker.getFragment(3)).parentId).to.equal(0);
      expect((await tracker.getFragment(2)).identification).to.equal(2);
      expect((await tracker.getFragment(2)).farmer).to.equal(outsider.address);
    });

    it("rejects non-registrars, zero size and zero farmer", async function () {
      await expect(
        tracker.connect(farmer).registerBatch(farmer.address, 100)
      ).to.be.revertedWith("Not registrar");
      await expect(
        tracker.connect(registrar).registerBatch(farmer.address, 0)
      ).to.be.revertedWith("Size must be > 0");
      await expect(
        tracker.connect(registrar).registerBatch(ethers.ZeroAddress, 5)
      ).to.be.revertedWith("Zero farmer");
      expect(await tracker.batchCount()).to.equal(0); // failed calls burn no id
    });
  });

  describe("fragment", function () {
    it("assigns contiguous offsets: box 3 of a 100kg batch in 10kg boxes starts at 20", async function () {
      await registerAndHandOver(); // fragment 2 = whole 100kg lot at distributor
      const sizes = Array(10).fill(10);
      const recipients = Array(10).fill(retailer1.address);
      const finals = Array(10).fill(false);
      await tracker.connect(distributor).fragment(2, sizes, recipients, finals);

      const children = await tracker.getChildren(2);
      expect(children.length).to.equal(10);
      const box3 = await tracker.getFragment(children[2]);
      expect(box3.offset).to.equal(20);
      expect(box3.size).to.equal(10);
      expect(box3.identification).to.equal(BATCH);
      expect(box3.mf).to.equal(true);
      expect(box3.df).to.equal(false);
      expect(await tracker.remaining(2)).to.equal(0);
    });

    it("keeps offsets absolute across levels and across several calls", async function () {
      await tracker.connect(registrar).registerBatch(farmer.address, 100);
      // farmer sells 60 then 30 to the distributor, keeps 10
      await tracker
        .connect(farmer)
        .fragment(1, [60], [distributor.address], [false]); // id 2: offset 0
      await tracker
        .connect(farmer)
        .fragment(1, [30], [distributor.address], [false]); // id 3: offset 60
      expect((await tracker.getFragment(2)).offset).to.equal(0);
      expect((await tracker.getFragment(3)).offset).to.equal(60);
      expect(await tracker.remaining(1)).to.equal(10);

      // distributor splits the 30kg lot (offset 60) into 10 + 20
      await tracker
        .connect(distributor)
        .fragment(
          3,
          [10, 20],
          [retailer1.address, retailer2.address],
          [false, false]
        );
      expect((await tracker.getFragment(4)).offset).to.equal(60);
      expect((await tracker.getFragment(5)).offset).to.equal(70);
    });

    it("blocks over-allocation, non-owners, bad input", async function () {
      await registerAndHandOver();
      await expect(
        tracker
          .connect(distributor)
          .fragment(2, [60, 50], [retailer1.address, retailer2.address], [false, false])
      ).to.be.revertedWith("Exceeds fragment size");
      await expect(
        tracker.connect(outsider).fragment(2, [10], [outsider.address], [false])
      ).to.be.revertedWith("Not fragment owner");
      await expect(
        tracker.connect(distributor).fragment(2, [10, 10], [retailer1.address], [false])
      ).to.be.revertedWith("Length mismatch");
      await expect(
        tracker.connect(distributor).fragment(2, [0], [retailer1.address], [false])
      ).to.be.revertedWith("Size must be > 0");
      await expect(
        tracker.connect(distributor).fragment(2, [10], [ethers.ZeroAddress], [false])
      ).to.be.revertedWith("Zero recipient");
      await expect(
        tracker.connect(distributor).fragment(99, [10], [retailer1.address], [false])
      ).to.be.revertedWith("Fragment not found");
    });

    it("never hands out the same range twice", async function () {
      await registerAndHandOver();
      await tracker
        .connect(distributor)
        .fragment(2, [70], [retailer1.address], [false]);
      // only 30 left, asking for 31 must fail
      await expect(
        tracker.connect(distributor).fragment(2, [31], [retailer2.address], [false])
      ).to.be.revertedWith("Exceeds fragment size");
      await tracker
        .connect(distributor)
        .fragment(2, [30], [retailer2.address], [false]);
      expect((await tracker.getFragment(4)).offset).to.equal(70);
      await expect(
        tracker.connect(distributor).fragment(2, [1], [retailer2.address], [false])
      ).to.be.revertedWith("Exceeds fragment size");
    });
  });

  describe("fragmentFor (registrar acts for the user)", function () {
    beforeEach(async function () {
      await tracker.connect(registrar).registerBatch(farmer.address, 100);
    });

    it("splits on behalf of the real owner", async function () {
      await tracker
        .connect(registrar)
        .fragmentFor(farmer.address, 1, [30], [distributor.address], [false]);
      const f = await tracker.getFragment(2);
      expect(f.owner).to.equal(distributor.address);
      expect(f.offset).to.equal(0);
      expect(await tracker.remaining(1)).to.equal(70);
    });

    it("rejects non-registrars and users that do not own the parent", async function () {
      await expect(
        tracker
          .connect(farmer)
          .fragmentFor(farmer.address, 1, [30], [distributor.address], [false])
      ).to.be.revertedWith("Not registrar");
      await expect(
        tracker
          .connect(registrar)
          .fragmentFor(outsider.address, 1, [30], [outsider.address], [false])
      ).to.be.revertedWith("Not fragment owner");
      // registrar itself owns nothing, can not split the farmer's batch as itself
      await expect(
        tracker
          .connect(registrar)
          .fragmentFor(registrar.address, 1, [30], [registrar.address], [false])
      ).to.be.revertedWith("Not fragment owner");
    });
  });

  describe("DF / final retail units", function () {
    beforeEach(async function () {
      await registerAndHandOver();
      await tracker
        .connect(distributor)
        .fragment(2, [40, 60], [retailer1.address, retailer2.address], [false, false]);
      // id 3: 40kg @0 -> retailer1, id 4: 60kg @40 -> retailer2
    });

    it("retailer splits into final packs (DF=true, MF=false) that cannot be split again", async function () {
      await tracker
        .connect(retailer1)
        .fragment(3, [20, 20], [retailer1.address, retailer1.address], [true, true]);
      const pack = await tracker.getFragment(5);
      expect(pack.df).to.equal(true);
      expect(pack.mf).to.equal(false);
      expect(pack.offset).to.equal(0);
      expect(
        (await tracker.getFragment(6)).offset
      ).to.equal(20);
      await expect(
        tracker.connect(retailer1).fragment(5, [5], [outsider.address], [true])
      ).to.be.revertedWith("DF set: cannot fragment");
    });

    it("markFinal works only for the owner and only on unsplit fragments", async function () {
      await expect(
        tracker.connect(outsider).markFinal(3)
      ).to.be.revertedWith("Not fragment owner");

      await tracker.connect(retailer1).markFinal(3);
      const f = await tracker.getFragment(3);
      expect(f.df).to.equal(true);
      expect(f.mf).to.equal(false);
      await expect(
        tracker.connect(retailer1).markFinal(3)
      ).to.be.revertedWith("Already final");

      // 4 gets split first, so it can no longer be marked final
      await tracker
        .connect(retailer2)
        .fragment(4, [10], [retailer2.address], [true]);
      await expect(
        tracker.connect(retailer2).markFinal(4)
      ).to.be.revertedWith("Already fragmented");
    });
  });

  describe("history and verification", function () {
    beforeEach(async function () {
      await registerAndHandOver(); // 1 root, 2 lot @ distributor
      await tracker
        .connect(distributor)
        .fragment(2, [40, 60], [retailer1.address, retailer2.address], [false, false]); // 3, 4
      await tracker
        .connect(retailer2)
        .fragment(4, [25, 35], [retailer2.address, retailer2.address], [true, true]); // 5 @40, 6 @65
    });

    it("getLineage returns the path from retail pack up to the farm batch", async function () {
      const path = await tracker.getLineage(6);
      expect(path.map((f) => Number(f.id))).to.deep.equal([6, 4, 2, 1]);
      path.forEach((f) => expect(f.identification).to.equal(BATCH));
      expect(path[0].offset).to.equal(65);
      expect(path[3].parentId).to.equal(0);
    });

    it("whole tree of a batch is rebuilt from FragmentCreated events", async function () {
      const ev = await tracker.queryFilter(tracker.filters.FragmentCreated(null, null, BATCH));
      expect(ev.map((e) => Number(e.args.id))).to.deep.equal([1, 2, 3, 4, 5, 6]);
      expect(ev.map((e) => Number(e.args.parentId))).to.deep.equal([0, 1, 2, 2, 4, 4]);
    });

    it("keeps trees of different batches apart", async function () {
      await tracker.connect(registrar).registerBatch(outsider.address, 40); // id 2, fragment 7
      const other = await tracker.queryFilter(tracker.filters.FragmentCreated(null, null, 2));
      const main = await tracker.queryFilter(tracker.filters.FragmentCreated(null, null, BATCH));
      expect(other.length).to.equal(1);
      expect(main.length).to.equal(6);
    });

    it("root totals: everything of the batch is handed out", async function () {
      const root = await tracker.getFragment(1);
      expect(root.size).to.equal(100);
      expect(await tracker.remaining(1)).to.equal(0);
    });

    it("verifyFragment accepts genuine labels and rejects forged ones", async function () {
      expect(await tracker.verifyFragment(6, BATCH, 65, 35)).to.equal(true);
      expect(await tracker.verifyFragment(6, BATCH, 60, 35)).to.equal(false); // forged offset
      expect(await tracker.verifyFragment(6, BATCH, 65, 36)).to.equal(false); // forged size
      expect(await tracker.verifyFragment(6, 2, 65, 35)).to.equal(false); // wrong batch
      expect(await tracker.verifyFragment(77, BATCH, 65, 35)).to.equal(false); // no such id
    });

    it("records custody changes and blocks the old holder afterwards", async function () {
      await tracker.connect(retailer1).transferFragment(3, outsider.address);
      const hist = await tracker.getCustodyHistory(3);
      expect(hist.length).to.equal(2);
      expect(hist[0].holder).to.equal(retailer1.address);
      expect(hist[1].holder).to.equal(outsider.address);
      await expect(
        tracker.connect(retailer1).fragment(3, [5], [retailer1.address], [false])
      ).to.be.revertedWith("Not fragment owner");
      await tracker.connect(outsider).fragment(3, [5], [outsider.address], [false]);
    });

    it("emits events usable for off-chain indexing", async function () {
      await expect(
        tracker.connect(retailer1).fragment(3, [10], [retailer1.address], [true])
      )
        .to.emit(tracker, "FragmentCreated")
        .withArgs(7, 3, BATCH, 0, 10, false, true, retailer1.address);
      await expect(tracker.connect(retailer1).transferFragment(7, outsider.address))
        .to.emit(tracker, "FragmentTransferred")
        .withArgs(7, retailer1.address, outsider.address);
    });
  });
});
