// SPDX-License-Identifier: MIT
pragma solidity ^0.8.30;

/// @title CropTracker
/// @notice Tracks how one farm batch is split into smaller packages as it moves
///         down the supply chain. Modelled on IP fragmentation:
///
///   identification : original farm batch id, identical on every fragment
///   offset         : absolute start position inside the ORIGINAL batch
///   size           : weight / quantity of this fragment
///   MF             : more fragments - fragment of a larger split, may be split again
///   DF             : do not fragment - final retail unit, can never be split
///
///   Root batch  : MF = false, DF = false   (parentId == 0)
///   Intermediate: MF = true,  DF = false
///   Final unit  : MF = false, DF = true
///
/// @dev The identification is generated by this contract (auto-increment), the
///      caller never chooses it. Only a registrar (the Farmer contract, set by
///      the owner) can register batches or fragment on behalf of a user.
///      Offsets are assigned by the contract from a per-fragment cursor, never
///      supplied by the caller. A fragment can only hand out ranges inside its
///      own [offset, offset + size) window and never hands out the same range
///      twice, so sibling fragments can not overlap and the total handed out can
///      not exceed the harvest. That is the anti-counterfeit guarantee.
contract CropTracker {
    struct Fragment {
        uint256 id; // globally unique fragment id (assigned by contract)
        uint256 identification; // farm batch id, same for every fragment of the batch
        address farmer; // farmer that registered the batch
        uint256 parentId; // 0 for the root batch
        uint256 offset; // absolute start inside the original batch
        uint256 size; // weight / quantity
        uint256 allocated; // part of `size` already carved into children
        bool mf; // more fragments
        bool df; // do not fragment
        address owner; // current holder
        uint256 createdAt;
    }

    struct Custody {
        address holder;
        uint256 timestamp;
    }

    uint256 public constant MAX_SPLIT = 50;
    uint256 public fragmentCount;
    // last identification handed out (identifications start at 1)
    uint256 public batchCount;

    address public owner;
    // contracts allowed to register batches / fragment on behalf of a user
    mapping(address => bool) public isRegistrar;

    mapping(uint256 => Fragment) private _fragments;
    mapping(uint256 => uint256[]) private _children;
    mapping(uint256 => Custody[]) private _custody;

    event BatchRegistered(
        uint256 indexed rootId,
        address indexed farmer,
        uint256 indexed identification,
        uint256 totalSize
    );
    event FragmentCreated(
        uint256 indexed id,
        uint256 indexed parentId,
        uint256 indexed identification,
        uint256 offset,
        uint256 size,
        bool mf,
        bool df,
        address owner
    );
    event FragmentTransferred(
        uint256 indexed id,
        address indexed from,
        address indexed to
    );
    event FragmentFinalized(uint256 indexed id);
    event RegistrarSet(address indexed registrar, bool allowed);

    modifier onlyRegistrar() {
        require(isRegistrar[msg.sender], "Not registrar");
        _;
    }

    constructor() {
        owner = msg.sender;
    }

    /// @notice Owner allows / removes a contract (e.g. Farmer) as registrar.
    function setRegistrar(address registrar, bool allowed) external {
        require(msg.sender == owner, "Not owner");
        require(registrar != address(0), "Zero registrar");
        isRegistrar[registrar] = allowed;
        emit RegistrarSet(registrar, allowed);
    }

    // ---------------------------------------------------------------------
    // Write functions
    // ---------------------------------------------------------------------

    /// @notice Registrar (Farmer contract) registers a harvest batch as the root
    ///         of a fragment tree. The identification is generated here.
    /// @param farmer the real farmer (end user) who owns the harvest
    /// @param totalSize total weight / quantity of the harvest
    function registerBatch(
        address farmer,
        uint256 totalSize
    ) external onlyRegistrar returns (uint256 identification, uint256 rootId) {
        require(farmer != address(0), "Zero farmer");
        require(totalSize > 0, "Size must be > 0");

        identification = ++batchCount;

        Fragment memory f;
        f.identification = identification;
        f.farmer = farmer;
        f.size = totalSize;
        f.owner = farmer;
        f.createdAt = block.timestamp;

        rootId = _store(f);
        emit BatchRegistered(rootId, farmer, identification, totalSize);
    }

    /// @notice Split part of a fragment into child fragments.
    /// @dev Offsets are assigned automatically and contiguously. Whatever is not
    ///      handed out stays with the parent (see `remaining`).
    /// @param parentId fragment being split (caller must own it)
    /// @param sizes size of each child
    /// @param recipients holder of each child (may be the caller)
    /// @param isFinal true = child is a final retail unit (DF set, MF cleared)
    function fragment(
        uint256 parentId,
        uint256[] memory sizes,
        address[] memory recipients,
        bool[] memory isFinal
    ) external returns (uint256[] memory) {
        return _fragment(msg.sender, parentId, sizes, recipients, isFinal);
    }

    /// @notice Same as `fragment`, but a registrar (Farmer contract) acts for
    ///         `caller`. `caller` must still own the parent fragment.
    function fragmentFor(
        address caller,
        uint256 parentId,
        uint256[] memory sizes,
        address[] memory recipients,
        bool[] memory isFinal
    ) external onlyRegistrar returns (uint256[] memory) {
        return _fragment(caller, parentId, sizes, recipients, isFinal);
    }

    function _fragment(
        address caller,
        uint256 parentId,
        uint256[] memory sizes,
        address[] memory recipients,
        bool[] memory isFinal
    ) private returns (uint256[] memory ids) {
        Fragment storage p = _fragments[parentId];
        require(p.id != 0, "Fragment not found");
        require(p.owner == caller, "Not fragment owner");
        require(!p.df, "DF set: cannot fragment");

        uint256 n = sizes.length;
        require(n > 0 && n <= MAX_SPLIT, "Bad split count");
        require(
            recipients.length == n && isFinal.length == n,
            "Length mismatch"
        );

        uint256 cursor = p.allocated;
        ids = new uint256[](n);

        for (uint256 i = 0; i < n; i++) {
            require(sizes[i] > 0, "Size must be > 0");
            require(recipients[i] != address(0), "Zero recipient");
            require(cursor + sizes[i] <= p.size, "Exceeds fragment size");

            Fragment memory c;
            c.identification = p.identification;
            c.farmer = p.farmer;
            c.parentId = parentId;
            c.offset = p.offset + cursor;
            c.size = sizes[i];
            c.mf = !isFinal[i];
            c.df = isFinal[i];
            c.owner = recipients[i];
            c.createdAt = block.timestamp;

            ids[i] = _store(c);
            cursor += sizes[i];
        }

        p.allocated = cursor;
    }

    /// @notice Mark a whole, unsplit fragment as a final retail unit (DF).
    function markFinal(uint256 id) external {
        Fragment storage f = _fragments[id];
        require(f.id != 0, "Fragment not found");
        require(f.owner == msg.sender, "Not fragment owner");
        require(!f.df, "Already final");
        require(f.allocated == 0, "Already fragmented");

        f.df = true;
        f.mf = false;
        emit FragmentFinalized(id);
    }

    /// @notice Hand a fragment (and any unsplit remainder) to a new holder.
    function transferFragment(uint256 id, address to) external {
        Fragment storage f = _fragments[id];
        require(f.id != 0, "Fragment not found");
        require(f.owner == msg.sender, "Not fragment owner");
        require(to != address(0), "Zero recipient");

        f.owner = to;
        _custody[id].push(Custody(to, block.timestamp));
        emit FragmentTransferred(id, msg.sender, to);
    }

    // ---------------------------------------------------------------------
    // Read functions
    // ---------------------------------------------------------------------

    function getFragment(uint256 id) external view returns (Fragment memory) {
        require(_fragments[id].id != 0, "Fragment not found");
        return _fragments[id];
    }

    /// @notice Part of the fragment not yet carved into children.
    function remaining(uint256 id) external view returns (uint256) {
        Fragment storage f = _fragments[id];
        require(f.id != 0, "Fragment not found");
        return f.size - f.allocated;
    }

    function getChildren(uint256 id) external view returns (uint256[] memory) {
        require(_fragments[id].id != 0, "Fragment not found");
        return _children[id];
    }

    /// @notice Every holder this fragment has had, oldest first.
    function getCustodyHistory(
        uint256 id
    ) external view returns (Custody[] memory) {
        require(_fragments[id].id != 0, "Fragment not found");
        return _custody[id];
    }

    /// @notice Path from a fragment up to the farm batch: [fragment, parent, ..., root].
    ///         Scan a retail package, call this, get its full provenance.
    function getLineage(
        uint256 id
    ) external view returns (Fragment[] memory path) {
        require(_fragments[id].id != 0, "Fragment not found");

        uint256 depth = 0;
        uint256 cur = id;
        while (cur != 0) {
            depth++;
            cur = _fragments[cur].parentId;
        }

        path = new Fragment[](depth);
        cur = id;
        for (uint256 i = 0; i < depth; i++) {
            path[i] = _fragments[cur];
            cur = _fragments[cur].parentId;
        }
    }

    /// @notice Anti-counterfeit check. A label carries (id, identification,
    ///         offset, size); true only if it matches the chain and the
    ///         fragment sits inside its parent's window.
    function verifyFragment(
        uint256 id,
        uint256 identification,
        uint256 offset,
        uint256 size
    ) external view returns (bool) {
        Fragment storage f = _fragments[id];
        if (f.id == 0) return false;
        if (
            f.identification != identification ||
            f.offset != offset ||
            f.size != size
        ) return false;

        if (f.parentId != 0) {
            Fragment storage p = _fragments[f.parentId];
            if (f.offset < p.offset) return false;
            if (f.offset + f.size > p.offset + p.allocated) return false;
        }
        return true;
    }

    // ---------------------------------------------------------------------
    // Internal
    // ---------------------------------------------------------------------

    function _store(Fragment memory f) private returns (uint256 id) {
        id = ++fragmentCount;
        f.id = id;
        _fragments[id] = f;
        _custody[id].push(Custody(f.owner, block.timestamp));
        if (f.parentId != 0) _children[f.parentId].push(id);

        emit FragmentCreated(
            id,
            f.parentId,
            f.identification,
            f.offset,
            f.size,
            f.mf,
            f.df,
            f.owner
        );
    }
}
