/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StakeholdersRouteImport } from './routes/stakeholders'
import { Route as TraceRouteImport } from './routes/trace'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardConsumerRouteImport } from './routes/dashboard.consumer'
import { Route as DashboardDistributorRouteImport } from './routes/dashboard.distributor'
import { Route as DashboardFarmerRouteImport } from './routes/dashboard.farmer'
import { Route as DashboardRetailerRouteImport } from './routes/dashboard.retailer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholdersRoute = StakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceRoute = TraceRouteImport.update({
  id: '/trace',
  path: '/trace',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardConsumerRoute = DashboardConsumerRouteImport.update({
  id: '/dashboard/consumer',
  path: '/dashboard/consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDistributorRoute = DashboardDistributorRouteImport.update({
  id: '/dashboard/distributor',
  path: '/dashboard/distributor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFarmerRoute = DashboardFarmerRouteImport.update({
  id: '/dashboard/farmer',
  path: '/dashboard/farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRetailerRoute = DashboardRetailerRouteImport.update({
  id: '/dashboard/retailer',
  path: '/dashboard/retailer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/stakeholders': typeof StakeholdersRoute
  '/trace': typeof TraceRoute
  '/traceability': typeof TraceabilityRoute
  '/dashboard/consumer': typeof DashboardConsumerRoute
  '/dashboard/distributor': typeof DashboardDistributorRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/dashboard/retailer': typeof DashboardRetailerRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/stakeholders': typeof StakeholdersRoute
  '/trace': typeof TraceRoute
  '/traceability': typeof TraceabilityRoute
  '/dashboard/consumer': typeof DashboardConsumerRoute
  '/dashboard/distributor': typeof DashboardDistributorRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/dashboard/retailer': typeof DashboardRetailerRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/stakeholders': typeof StakeholdersRoute
  '/trace': typeof TraceRoute
  '/traceability': typeof TraceabilityRoute
  '/dashboard/consumer': typeof DashboardConsumerRoute
  '/dashboard/distributor': typeof DashboardDistributorRoute
  '/dashboard/farmer': typeof DashboardFarmerRoute
  '/dashboard/retailer': typeof DashboardRetailerRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/marketplace'
    | '/profile'
    | '/register'
    | '/settings'
    | '/stakeholders'
    | '/trace'
    | '/traceability'
    | '/dashboard/consumer'
    | '/dashboard/distributor'
    | '/dashboard/farmer'
    | '/dashboard/retailer'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/marketplace'
    | '/profile'
    | '/register'
    | '/settings'
    | '/stakeholders'
    | '/trace'
    | '/traceability'
    | '/dashboard/consumer'
    | '/dashboard/distributor'
    | '/dashboard/farmer'
    | '/dashboard/retailer'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/marketplace'
    | '/profile'
    | '/register'
    | '/settings'
    | '/stakeholders'
    | '/trace'
    | '/traceability'
    | '/dashboard/consumer'
    | '/dashboard/distributor'
    | '/dashboard/farmer'
    | '/dashboard/retailer'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  StakeholdersRoute: typeof StakeholdersRoute
  TraceRoute: typeof TraceRoute
  TraceabilityRoute: typeof TraceabilityRoute
  DashboardConsumerRoute: typeof DashboardConsumerRoute
  DashboardDistributorRoute: typeof DashboardDistributorRoute
  DashboardFarmerRoute: typeof DashboardFarmerRoute
  DashboardRetailerRoute: typeof DashboardRetailerRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholders': {
      id: '/stakeholders'
      path: '/stakeholders'
      fullPath: '/stakeholders'
      preLoaderRoute: typeof StakeholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trace': {
      id: '/trace'
      path: '/trace'
      fullPath: '/trace'
      preLoaderRoute: typeof TraceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/consumer': {
      id: '/dashboard/consumer'
      path: '/dashboard/consumer'
      fullPath: '/dashboard/consumer'
      preLoaderRoute: typeof DashboardConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/distributor': {
      id: '/dashboard/distributor'
      path: '/dashboard/distributor'
      fullPath: '/dashboard/distributor'
      preLoaderRoute: typeof DashboardDistributorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/farmer': {
      id: '/dashboard/farmer'
      path: '/dashboard/farmer'
      fullPath: '/dashboard/farmer'
      preLoaderRoute: typeof DashboardFarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/retailer': {
      id: '/dashboard/retailer'
      path: '/dashboard/retailer'
      fullPath: '/dashboard/retailer'
      preLoaderRoute: typeof DashboardRetailerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  StakeholdersRoute: StakeholdersRoute,
  TraceRoute: TraceRoute,
  TraceabilityRoute: TraceabilityRoute,
  DashboardConsumerRoute: DashboardConsumerRoute,
  DashboardDistributorRoute: DashboardDistributorRoute,
  DashboardFarmerRoute: DashboardFarmerRoute,
  DashboardRetailerRoute: DashboardRetailerRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
